//
//  CreateUserInteractorTests.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import POCClean
import XCTest

class CreateUserInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: CreateUserInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupCreateUserInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCreateUserInteractor()
    {
        sut = CreateUserInteractor()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    
    func testInteractorCallsPresenter(){
        
        //Given 
        let spy = PresenterSpy()
        sut.presenter = spy
        
        // When
        let request = CreateUser.User.Request(firstName: "Alejandro", lastName: "Rodríguez")
        sut.saveUser(request: request)
        
        //Then 
        XCTAssertTrue(spy.presentUserWasCalled, "Present create user should be called")
    }
    
    func testInteractorShouldCallWorkerToSaveUser(){
        
        //Given
        let spy = WorkerSpy(store: UsersMemStore())
        sut.worker = spy
        
        // When
        let request = CreateUser.User.Request(firstName: "Alejandro", lastName: "Rodríguez")
        sut.saveUser(request: request)
        
        XCTAssertTrue(spy.workerWasCalled, "Worker should have been called")
        
        
    }
}

class WorkerSpy:CreateUserWorker{
    
    var workerWasCalled = false
    
    
    
    override func saveUser(request: CreateUser.User.Request, completionHandler: (String) -> Void) {
         workerWasCalled = true
    }
    
    
}

class PresenterSpy: CreateUserPresentationLogic{
    
    
    var presentUserWasCalled = false
    
    func presentCreateUser(response: CreateUser.User.Response) {
        presentUserWasCalled = true
    }
}
