//
//  CreateUserPresenterTests.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import POCClean
import XCTest

class CreateUserPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: CreateUserPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupCreateUserPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCreateUserPresenter()
    {
        sut = CreateUserPresenter()
    }
    
    // MARK: Test doubles
    
    // MARK: Tests
    
    func testVCIsCalledAfterUserIsSaved(){
        
        //Given
        let spy = ViewControllerSpy()
        sut.viewController = spy
        
        
        //When
        let response = CreateUser.User.Response(success: "User was saved succesfully")
        sut.presentCreateUser(response: response)
        
        //Then 
        XCTAssertTrue(spy.viewControllerWasCalled, "View controller has to be called")
    }
}

class ViewControllerSpy: CreateUserDisplayLogic{
    
    var viewControllerWasCalled = false
    
    func displayCreateUserResponse(viewModel: CreateUser.User.ViewModel) {
        viewControllerWasCalled = true
    }
}
