//
//  CreateUserInteractor.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserBusinessLogic
{
    
    func saveUser()
}

protocol CreateUserDataStore
{
    //var name: String { get set }
}

class CreateUserInteractor: CreateUserBusinessLogic, CreateUserDataStore
{
    var presenter: CreateUserPresentationLogic?
    var worker: CreateUserWorker?
    //var name: String = ""
    
    // MARK: Do something
    
//    func doSomething(request: CreateUser.Something.Request)
//    {
//        worker = CreateUserWorker()
//        worker?.doSomeWork()
//        
//        let response = CreateUser.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
    
    func saveUser() {}
}
