//
//  CreateUserWorker.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UsersStoreProtocol {
    
    func saveUser(request: CreateUser.User.Request, completionHandler: (_ success: String) -> Void)
}


class CreateUserWorker
{
    var usersStore:UsersStoreProtocol
    
    init(store: UsersStoreProtocol) {
        usersStore = store
    }
    
    
    func saveUser(request: CreateUser.User.Request, completionHandler: (_ success: String) -> Void){
        usersStore.saveUser(request: request) { (success) in
            completionHandler("Success")
        }
    }
    
}
