//
//  ListUsersPresenter.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUsersPresentationLogic
{
  func presentSomething(response: ListUsers.Something.Response)
}

class ListUsersPresenter: ListUsersPresentationLogic
{
  weak var viewController: ListUsersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListUsers.Something.Response)
  {
    let viewModel = ListUsers.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
