//
//  ListUsersInteractor.swift
//  POCClean
//
//  Created by Alejandro Rodriguez on 7/5/17.
//  Copyright (c) 2017 Alejandro Rodriguez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListUsersBusinessLogic
{
  func doSomething(request: ListUsers.Something.Request)
}

protocol ListUsersDataStore
{
  //var name: String { get set }
}

class ListUsersInteractor: ListUsersBusinessLogic, ListUsersDataStore
{
  var presenter: ListUsersPresentationLogic?
  var worker: ListUsersWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListUsers.Something.Request)
  {
    worker = ListUsersWorker()
    worker?.doSomeWork()
    
    let response = ListUsers.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
